FROM debian:jessie-slim

RUN apt-get update && apt-get install wget bzip2 -y
RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
RUN bash miniconda.sh -b -p /opt/conda
ENV PATH /opt/conda/bin:$PATH

RUN conda install pytorch-cpu torchvision-cpu -c pytorch
